In [1]:
import numpy as np
import sklearn

In [2]:
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans

In [3]:
import pandas as pd

In [4]:
pd.read_csv("agr_en_train.csv")

,facebook_corpus_msr_1723796,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
0,facebook_corpus_msr_466073,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
1,facebook_corpus_msr_1493901,"Now question is, Pakistan will adhere to this?",OAG
2,facebook_corpus_msr_405512,Pakistan is comprised of fake muslims who does...,OAG
3,facebook_corpus_msr_1521685,"??we r against cow slaughter,so of course it w...",NAG
4,facebook_corpus_msr_462570,Wondering why Educated Ambassador is strugglin...,CAG
...,...,...,...
11993,facebook_corpus_msr_394638,They belong to you flight dirty terrorist coun...,OAG
11994,facebook_corpus_msr_429177,"Really motivating programme, congratulations t...",NAG
11995,facebook_corpus_msr_2032370,fabricated news,OAG
11996,facebook_corpus_msr_1722926,What's wrong with you secular idiots,OAG
11997,facebook_corpus_msr_327960,Looks like inevitable after all political hard...,NAG

In [5]:
df = pd.DataFrame(pd.read_csv("agr_en_train.csv"))

In [6]:
df

,facebook_corpus_msr_1723796,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
0,facebook_corpus_msr_466073,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
1,facebook_corpus_msr_1493901,"Now question is, Pakistan will adhere to this?",OAG
2,facebook_corpus_msr_405512,Pakistan is comprised of fake muslims who does...,OAG
3,facebook_corpus_msr_1521685,"??we r against cow slaughter,so of course it w...",NAG
4,facebook_corpus_msr_462570,Wondering why Educated Ambassador is strugglin...,CAG
...,...,...,...
11993,facebook_corpus_msr_394638,They belong to you flight dirty terrorist coun...,OAG
11994,facebook_corpus_msr_429177,"Really motivating programme, congratulations t...",NAG
11995,facebook_corpus_msr_2032370,fabricated news,OAG
11996,facebook_corpus_msr_1722926,What's wrong with you secular idiots,OAG
11997,facebook_corpus_msr_327960,Looks like inevitable after all political hard...,NAG

In [8]:
df.pop(1)

KeyError: 1

In [9]:
df = df.iloc[:,1:]

In [10]:
df

,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
0,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
1,"Now question is, Pakistan will adhere to this?",OAG
2,Pakistan is comprised of fake muslims who does...,OAG
3,"??we r against cow slaughter,so of course it w...",NAG
4,Wondering why Educated Ambassador is strugglin...,CAG
...,...,...
11993,They belong to you flight dirty terrorist coun...,OAG
11994,"Really motivating programme, congratulations t...",NAG
11995,fabricated news,OAG
11996,What's wrong with you secular idiots,OAG
11997,Looks like inevitable after all political hard...,NAG

In [11]:
df[2]

KeyError: 2

In [12]:
df["oag"]

KeyError: 'oag'

In [13]:
df.describe()

,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
count,11998,11998
unique,11643,3
top,Gandhi Killer Ram (Nathu) Temple in India........,NAG
freq,14,5051

In [14]:
df.coloumns = ["text","offensive"]

C:\Users\Madhu\AppData\Local\Temp/ipykernel_17228/573664633.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.coloumns = ["text","offensive"]

In [15]:
df

,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
0,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
1,"Now question is, Pakistan will adhere to this?",OAG
2,Pakistan is comprised of fake muslims who does...,OAG
3,"??we r against cow slaughter,so of course it w...",NAG
4,Wondering why Educated Ambassador is strugglin...,CAG
...,...,...
11993,They belong to you flight dirty terrorist coun...,OAG
11994,"Really motivating programme, congratulations t...",NAG
11995,fabricated news,OAG
11996,What's wrong with you secular idiots,OAG
11997,Looks like inevitable after all political hard...,NAG

In [16]:
df.coloumns

['text', 'offensive']

In [17]:
df

,Well said sonu..you have courage to stand against dadagiri of Muslims,OAG
0,"Most of Private Banks ATM's Like HDFC, ICICI e...",NAG
1,"Now question is, Pakistan will adhere to this?",OAG
2,Pakistan is comprised of fake muslims who does...,OAG
3,"??we r against cow slaughter,so of course it w...",NAG
4,Wondering why Educated Ambassador is strugglin...,CAG
...,...,...
11993,They belong to you flight dirty terrorist coun...,OAG
11994,"Really motivating programme, congratulations t...",NAG
11995,fabricated news,OAG
11996,What's wrong with you secular idiots,OAG
11997,Looks like inevitable after all political hard...,NAG

In [18]:
df[]

SyntaxError: invalid syntax (Temp/ipykernel_17228/1951995059.py, line 1)

In [19]:
df["text"]

KeyError: 'text'

In [20]:
print(df)

      Well said sonu..you have courage to stand against dadagiri of Muslims  \
0      Most of Private Banks ATM's Like HDFC, ICICI e...
1         Now question is, Pakistan will adhere to this?
2      Pakistan is comprised of fake muslims who does...
3      ??we r against cow slaughter,so of course it w...
4      Wondering why Educated Ambassador is strugglin...
...                                                  ...
11993  They belong to you flight dirty terrorist coun...
11994  Really motivating programme, congratulations t...
11995                                    fabricated news
11996               What's wrong with you secular idiots
11997  Looks like inevitable after all political hard...

       OAG
0      NAG
1      OAG
2      OAG
3      NAG
4      CAG
...    ...
11993  OAG
11994  NAG
11995  OAG
11996  OAG
11997  NAG

[11998 rows x 2 columns]

In [ ]:
df.column